# Site settings
title: "#DinnerMode"
email: gerard@revelry.co
description: > # this means to ignore newlines until "baseurl:"
  Put your phone down please.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dinnermode.org" # the base hostname & protocol for your site
twitter_username: dinnermode
github_username:  dinnermode

# Build settings
markdown: kramdown
